# Generated by Django 5.2.5 on 2025-11-22 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn_number', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spn_number', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('source_file', models.CharField(blank=True, max_length=512)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePGN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.pgn')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'pgn')},
            },
        ),
        migrations.CreateModel(
            name='VehicleSPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('supported', models.BooleanField(default=False)),
                ('spn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.spn')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'spn')},
            },
        ),
    ]
