# Generated by Django 4.2.17 on 2025-12-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Untitled', max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('Published_Date', models.DateField()),
                ('Resource', models.URLField(blank=True)),
                ('File', models.FileField(upload_to='auxiliary_files/%Y/%m/%d/')),
                ('Note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='J1939ParameterDefinition',
            fields=[
                ('SPN_Number', models.IntegerField(help_text='Suspect Parameter Number (unique identifier)', primary_key=True, serialize=False)),
                ('PGN_DEC', models.IntegerField(help_text='Parameter Group Number in decimal format')),
                ('PGN_HEX', models.CharField(blank=True, help_text='Parameter Group Number in hexadecimal format', max_length=10)),
                ('SPN_Description', models.CharField(help_text='Human-readable description of the parameter', max_length=255)),
                ('Unit', models.CharField(help_text='Unit of measurement (e.g., km/h, %, L, s)', max_length=50)),
                ('Data_Length_Bytes', models.IntegerField(help_text='Number of bytes used for this SPN')),
                ('Start_Byte', models.IntegerField(help_text='Starting byte position in CAN message (1-8)')),
                ('Start_Bit', models.IntegerField(default=0, help_text='Starting bit position within the byte (0-7)')),
                ('Bit_Length', models.IntegerField(help_text='Total number of bits for this SPN value')),
                ('Resolution', models.FloatField(help_text='Scaling factor (multiply raw value by this)')),
                ('Offset', models.FloatField(default=0.0, help_text='Offset to add after scaling')),
                ('Min_Value', models.FloatField(blank=True, help_text='Minimum valid physical value', null=True)),
                ('Max_Value', models.FloatField(blank=True, help_text='Maximum valid physical value', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'J1939 Parameter Definition',
                'verbose_name_plural': 'J1939 Parameter Definitions',
                'ordering': ['PGN_DEC', 'SPN_Number'],
            },
        ),
        migrations.CreateModel(
            name='PGN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn_number', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spn_number', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StandardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Standard_No', models.CharField(max_length=100, unique=True)),
                ('Standard_Name', models.CharField(max_length=255)),
                ('Issued_Date', models.DateField()),
                ('Revised_Date', models.DateField(blank=True, null=True)),
                ('Resource', models.URLField(blank=True)),
                ('File', models.FileField(upload_to='standard_files/%Y/%m/%d/')),
                ('Note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('source_file', models.CharField(blank=True, max_length=512)),
                ('excel_file', models.FileField(blank=True, help_text='Original Excel file for auditing', null=True, upload_to='j1939_uploads/%Y/%m/%d/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('supported', models.BooleanField(default=False)),
                ('pgn', models.ForeignKey(blank=True, help_text='Optional PGN associated with this SPN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.pgn')),
                ('spn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.spn')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePGN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.pgn')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.vehicle')),
            ],
        ),
    ]
