# Generated by Django 5.2.5 on 2025-11-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='excel_file',
            field=models.FileField(blank=True, help_text='Original Excel file for auditing', null=True, upload_to='j1939_uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='vehiclespn',
            name='pgn',
            field=models.ForeignKey(blank=True, help_text='Optional PGN associated with this SPN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.pgn'),
        ),
    ]
