# Generated by Django 5.2.5 on 2025-12-16 07:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_update_standard_auxiliary_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxiliaryfile',
            name='File_Name',
        ),
        migrations.RemoveField(
            model_name='auxiliaryfile',
            name='Keyin_Date',
        ),
        migrations.RemoveField(
            model_name='auxiliaryfile',
            name='Keyin_Person',
        ),
        migrations.RemoveField(
            model_name='standardfile',
            name='Keyin_Date',
        ),
        migrations.RemoveField(
            model_name='standardfile',
            name='Keyin_Person',
        ),
        migrations.AddField(
            model_name='auxiliaryfile',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.category'),
        ),
        migrations.AddField(
            model_name='auxiliaryfile',
            name='Title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='auxiliaryfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auxiliaryfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auxiliaryfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standardfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='standardfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auxiliaryfile',
            name='Resource',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='standardfile',
            name='Resource',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='standardfile',
            name='Standard_Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='standardfile',
            name='Standard_No',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='J1939ParameterDefinition',
            fields=[
                ('SPN_Number', models.IntegerField(help_text='Suspect Parameter Number (unique identifier)', primary_key=True, serialize=False)),
                ('PGN_DEC', models.IntegerField(help_text='Parameter Group Number in decimal format')),
                ('PGN_HEX', models.CharField(blank=True, help_text='Parameter Group Number in hexadecimal format', max_length=10)),
                ('SPN_Description', models.CharField(help_text='Human-readable description of the parameter', max_length=255)),
                ('Unit', models.CharField(help_text='Unit of measurement (e.g., km/h, %, L, s)', max_length=50)),
                ('Data_Length_Bytes', models.IntegerField(help_text='Number of bytes used for this SPN')),
                ('Start_Byte', models.IntegerField(help_text='Starting byte position in CAN message (1-8)')),
                ('Start_Bit', models.IntegerField(default=0, help_text='Starting bit position within the byte (0-7)')),
                ('Bit_Length', models.IntegerField(help_text='Total number of bits for this SPN value')),
                ('Resolution', models.FloatField(help_text='Scaling factor (multiply raw value by this)')),
                ('Offset', models.FloatField(default=0.0, help_text='Offset to add after scaling')),
                ('Min_Value', models.FloatField(blank=True, help_text='Minimum valid physical value', null=True)),
                ('Max_Value', models.FloatField(blank=True, help_text='Maximum valid physical value', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Standard_Reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_definitions', to='Main.standardfile')),
            ],
            options={
                'verbose_name': 'J1939 Parameter Definition',
                'verbose_name_plural': 'J1939 Parameter Definitions',
                'ordering': ['PGN_DEC', 'SPN_Number'],
            },
        ),
    ]
